version: "3.8"

services:
  php:
    build:
      context: ./appdaf
      dockerfile: ../.docker/php/Dockerfile
    container_name: woyofal_php
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pgdbwoyofal
      DB_USER: pguser
      DB_PASSWORD: pgpassword
    volumes:
      - ./appdaf/public:/var/www/html/public
      - ./appdaf/.env:/var/www/html/.env
    networks:
      - backend
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: woyofal_nginx
    depends_on:
      - php
    ports:
      - "8082:80"
    volumes:
      - ./appdaf/public:/var/www/html/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  postgres:
    container_name: postgresWoyofal
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: pgdbwoyofal
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    container_name: woyofal_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5052:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  pg_data:
  pgadmin_data:

networks:
  backend:
